
[package]
name = "winrt-system-sys"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core-sys = { path = "../../libs/windows-core-sys",  version = "0.37.0" }
winrt-foundation-sys = { path = "../winrt-foundation-sys",  version = "0.37.0", optional = true }

[features]
deprecated = []
default = ["winrt-foundation-sys"]
Diagnostics = []
Diagnostics_DevicePortal = ["Diagnostics"]
Diagnostics_Telemetry = ["Diagnostics"]
Diagnostics_TraceReporting = ["Diagnostics"]
Display = []
Implementation = []
Implementation_FileExplorer = ["Implementation"]
Inventory = []
Power = []
Power_Diagnostics = ["Power"]
Preview = []
Profile = []
Profile_SystemManufacturers = ["Profile"]
RemoteDesktop = []
RemoteDesktop_Input = ["RemoteDesktop"]
RemoteSystems = []
Threading = []
Threading_Core = ["Threading"]
Update = []
UserProfile = []
