
[package]
name = "windows-win32-system"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core = { path = "../../libs/windows-core",  version = "0.37.0" }

[features]
default = []
deprecated = []
AddressBook = []
Antimalware = []
ApplicationInstallationAndServicing = []
ApplicationVerifier = []
AssessmentTool = []
Com = []
Com_CallObj = ["Com"]
Com_ChannelCredentials = ["Com"]
Com_Events = ["Com"]
Com_Marshal = ["Com"]
Com_StructuredStorage = ["Com"]
Com_UI = ["Com"]
Com_Urlmon = ["Com"]
ComponentServices = []
Console = []
Contacts = []
CorrelationVector = []
DataExchange = []
DeploymentServices = []
DesktopSharing = []
DeveloperLicensing = []
Diagnostics = []
Diagnostics_Ceip = ["Diagnostics"]
Diagnostics_Debug = ["Diagnostics"]
Diagnostics_Debug_WebApp = ["Diagnostics_Debug"]
Diagnostics_Etw = ["Diagnostics"]
Diagnostics_ProcessSnapshotting = ["Diagnostics"]
Diagnostics_ToolHelp = ["Diagnostics"]
DistributedTransactionCoordinator = []
Environment = []
ErrorReporting = []
EventCollector = []
EventLog = []
EventNotificationService = []
GroupPolicy = []
HostCompute = []
HostComputeNetwork = []
HostComputeSystem = []
Hypervisor = []
IO = []
Iis = []
Ioctl = []
JobObjects = []
Js = []
Kernel = []
LibraryLoader = []
Mailslots = []
Mapi = []
Memory = []
Memory_NonVolatile = ["Memory"]
MessageQueuing = []
MixedReality = []
Mmc = []
Ole = []
ParentalControls = []
PasswordManagement = []
Performance = []
Performance_HardwareCounterProfiling = ["Performance"]
Pipes = []
Power = []
ProcessStatus = []
RealTimeCommunications = []
Recovery = []
Registry = []
RemoteAssistance = []
RemoteDesktop = []
RemoteManagement = []
RestartManager = []
Restore = []
Rpc = []
Search = []
Search_Common = ["Search"]
SecurityCenter = []
ServerBackup = []
Services = []
SettingsManagementInfrastructure = []
SetupAndMigration = []
Shutdown = []
SideShow = []
StationsAndDesktops = []
SubsystemForLinux = []
SystemInformation = []
SystemServices = []
TaskScheduler = []
Threading = []
Time = []
TpmBaseServices = []
TransactionServer = []
UpdateAgent = []
UpdateAssessment = []
UserAccessLogging = []
VirtualDosMachines = []
WinRT = []
WinRT_AllJoyn = ["WinRT"]
WinRT_Composition = ["WinRT"]
WinRT_CoreInputView = ["WinRT"]
WinRT_Direct3D11 = ["WinRT"]
WinRT_Display = ["WinRT"]
WinRT_Graphics = ["WinRT"]
WinRT_Graphics_Capture = ["WinRT_Graphics"]
WinRT_Graphics_Direct2D = ["WinRT_Graphics"]
WinRT_Graphics_Imaging = ["WinRT_Graphics"]
WinRT_Holographic = ["WinRT"]
WinRT_Isolation = ["WinRT"]
WinRT_ML = ["WinRT"]
WinRT_Media = ["WinRT"]
WinRT_Pdf = ["WinRT"]
WinRT_Printing = ["WinRT"]
WinRT_Shell = ["WinRT"]
WinRT_Storage = ["WinRT"]
WinRT_Xaml = ["WinRT"]
WindowsProgramming = []
WindowsSync = []
Wmi = []
