
[package]
name = "windows-win32-storage"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core = { path = "../../libs/windows-core",  version = "0.37.0" }

[features]
default = []
deprecated = []
Cabinets = []
CloudFilters = []
Compression = []
DataDeduplication = []
DistributedFileSystem = []
EnhancedStorage = []
FileHistory = []
FileServerResourceManager = []
FileSystem = []
Imapi = []
IndexServer = []
InstallableFileSystems = []
IscsiDisc = []
Jet = []
OfflineFiles = []
OperationRecorder = []
Packaging = []
Packaging_Appx = ["Packaging"]
Packaging_Opc = ["Packaging"]
ProjectedFileSystem = []
StructuredStorage = []
Vhd = []
VirtualDiskService = []
Vss = []
Xps = []
Xps_Printing = ["Xps"]
