
[package]
name = "winrt-phone-sys"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core-sys = { path = "../../libs/windows-core-sys",  version = "0.37.0" }
winrt-foundation-sys = { path = "../winrt-foundation-sys",  version = "0.37.0", optional = true }

[features]
deprecated = []
default = ["winrt-foundation-sys"]
ApplicationModel = []
Devices = []
Devices_Notification = ["Devices"]
Devices_Power = ["Devices"]
Management = []
Management_Deployment = ["Management"]
Media = []
Media_Devices = ["Media"]
Notification = []
Notification_Management = ["Notification"]
PersonalInformation = []
PersonalInformation_Provisioning = ["PersonalInformation"]
Speech = []
Speech_Recognition = ["Speech"]
StartScreen = []
System = []
System_Power = ["System"]
System_Profile = ["System"]
System_UserProfile = ["System"]
System_UserProfile_GameServices = ["System_UserProfile"]
System_UserProfile_GameServices_Core = ["System_UserProfile_GameServices"]
UI = []
UI_Input = ["UI"]
