
[package]
name = "win32-graphics"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core = { path = "../../libs/windows-core",  version = "0.37.0" }
win32-foundation = { path = "../win32-foundation",  version = "0.37.0", optional = true }

[features]
deprecated = []
default = ["win32-foundation"]
CompositionSwapchain = []
DXCore = []
Direct2D = []
Direct2D_Common = ["Direct2D"]
Direct3D = []
Direct3D_Dxc = ["Direct3D"]
Direct3D_Fxc = ["Direct3D"]
Direct3D10 = []
Direct3D11 = []
Direct3D11on12 = []
Direct3D12 = []
Direct3D9 = []
Direct3D9on12 = []
DirectComposition = []
DirectDraw = []
DirectManipulation = []
DirectWrite = []
Dwm = []
Dxgi = []
Dxgi_Common = ["Dxgi"]
Gdi = []
Hlsl = []
Imaging = []
Imaging_D2D = ["Imaging"]
OpenGL = []
Printing = []
Printing_PrintTicket = ["Printing"]
