
[package]
name = "win32-networking"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core = { path = "../../libs/windows-core",  version = "0.37.0" }
win32-foundation = { path = "../win32-foundation",  version = "0.37.0", optional = true }

[features]
deprecated = []
default = ["win32-foundation"]
ActiveDirectory = []
BackgroundIntelligentTransferService = []
Clustering = []
HttpServer = []
Ldap = []
NetworkListManager = []
RemoteDifferentialCompression = []
WebSocket = []
WinHttp = []
WinInet = []
WinSock = []
WindowsWebServices = []
