
[package]
name = "windows-sys-ui"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-sys-core = { path = "../../libs/windows-sys-core",  version = "0.37.0" }

[features]
default = []
deprecated = []
Accessibility = []
ApplicationSettings = []
Composition = []
Composition_Core = ["Composition"]
Composition_Desktop = ["Composition"]
Composition_Diagnostics = ["Composition"]
Composition_Effects = ["Composition"]
Composition_Interactions = ["Composition"]
Composition_Scenes = ["Composition"]
Core = []
Core_AnimationMetrics = ["Core"]
Core_Preview = ["Core"]
Input = []
Input_Core = ["Input"]
Input_Inking = ["Input"]
Input_Inking_Analysis = ["Input_Inking"]
Input_Inking_Core = ["Input_Inking"]
Input_Inking_Preview = ["Input_Inking"]
Input_Preview = ["Input"]
Input_Preview_Injection = ["Input_Preview"]
Input_Spatial = ["Input"]
Notifications = []
Notifications_Management = ["Notifications"]
Popups = []
Shell = []
StartScreen = []
Text = []
Text_Core = ["Text"]
UIAutomation = []
UIAutomation_Core = ["UIAutomation"]
ViewManagement = []
ViewManagement_Core = ["ViewManagement"]
WebUI = []
WebUI_Core = ["WebUI"]
WindowManagement = []
WindowManagement_Preview = ["WindowManagement"]
Xaml = []
Xaml_Automation = ["Xaml"]
Xaml_Automation_Peers = ["Xaml_Automation"]
Xaml_Automation_Provider = ["Xaml_Automation"]
Xaml_Automation_Text = ["Xaml_Automation"]
Xaml_Controls = ["Xaml"]
Xaml_Controls_Maps = ["Xaml_Controls"]
Xaml_Controls_Primitives = ["Xaml_Controls"]
Xaml_Core = ["Xaml"]
Xaml_Core_Direct = ["Xaml_Core"]
Xaml_Data = ["Xaml"]
Xaml_Documents = ["Xaml"]
Xaml_Hosting = ["Xaml"]
Xaml_Input = ["Xaml"]
Xaml_Interop = ["Xaml"]
Xaml_Markup = ["Xaml"]
Xaml_Media = ["Xaml"]
Xaml_Media_Animation = ["Xaml_Media"]
Xaml_Media_Imaging = ["Xaml_Media"]
Xaml_Media_Media3D = ["Xaml_Media"]
Xaml_Navigation = ["Xaml"]
Xaml_Printing = ["Xaml"]
Xaml_Resources = ["Xaml"]
Xaml_Shapes = ["Xaml"]
