[package]
name = "provider"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.41.0"
features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_WindowsAndMessaging",
]

[dependencies.windows_widgets]
path = "../windows_widgets"