
[package]
name = "winrt-graphics"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core = { path = "../../libs/windows-core",  version = "0.37.0" }
winrt-foundation = { path = "../winrt-foundation",  version = "0.37.0", optional = true }

[features]
deprecated = []
default = ["winrt-foundation"]
Capture = []
DirectX = []
DirectX_Direct3D11 = ["DirectX"]
Display = []
Display_Core = ["Display"]
Effects = []
Holographic = []
Imaging = []
Printing = []
Printing_OptionDetails = ["Printing"]
Printing_PrintSupport = ["Printing"]
Printing_PrintTicket = ["Printing"]
Printing_Workflow = ["Printing"]
Printing3D = []
