
[package]
name = "windows-devices"
version = "0.37.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Windows"
repository = "https://github.com/microsoft/windows-rs"
readme = "../../../.github/readme.md"
rust-version = "1.46"

[dependencies]
windows-core = { path = "../../libs/windows-core",  version = "0.37.0" }

[features]
default = []
deprecated = []
Adc = []
Adc_Provider = ["Adc"]
AllJoyn = []
Background = []
Bluetooth = []
Bluetooth_Advertisement = ["Bluetooth"]
Bluetooth_Background = ["Bluetooth"]
Bluetooth_GenericAttributeProfile = ["Bluetooth"]
Bluetooth_Rfcomm = ["Bluetooth"]
Custom = []
Display = []
Display_Core = ["Display"]
Enumeration = []
Enumeration_Pnp = ["Enumeration"]
Geolocation = []
Geolocation_Geofencing = ["Geolocation"]
Gpio = []
Gpio_Provider = ["Gpio"]
Haptics = []
HumanInterfaceDevice = []
I2c = []
I2c_Provider = ["I2c"]
Input = []
Input_Preview = ["Input"]
Lights = []
Lights_Effects = ["Lights"]
Midi = []
Perception = []
Perception_Provider = ["Perception"]
PointOfService = []
PointOfService_Provider = ["PointOfService"]
Portable = []
Power = []
Printers = []
Printers_Extensions = ["Printers"]
Pwm = []
Pwm_Provider = ["Pwm"]
Radios = []
Scanners = []
Sensors = []
Sensors_Custom = ["Sensors"]
SerialCommunication = []
SmartCards = []
Sms = []
Spi = []
Spi_Provider = ["Spi"]
Usb = []
WiFi = []
WiFiDirect = []
WiFiDirect_Services = ["WiFiDirect"]
